### PR TITLE
Move towards a more functional approach

### PR DESCRIPTION
**Pull request by keyvanakbary**

### CODE REVIEW

**Comment by mbrevda** [comment]
Yay for backward incompatible breaking changes! /s

What was the idea here?

**Comment by keyvanakbary** [comment]
Hey @mbrevda, the idea is to move away from a fake Object-Oriented model (with no encapsulated state at all). We should have just pure functions.

As you said, this is backward incompatible. That's why, following [SemVer](http://semver.org/), there was a version bump from v2.0.x to [v3.0.x](https://github.com/keyvanakbary/slugifier/releases/tag/v3.0.0). I even released a more drastic update, the [v4.0.0](https://github.com/keyvanakbary/slugifier/releases/tag/v4.0.0) with support only for PHP 5.6 and 7. You could take a look to all available versions and requirements on [Slugifier's Packagist page](https://packagist.org/packages/keyvanakbary/slugifier).

If your `composer.json` points to version 2.0.x (the OO version), you should have no problem with this update at all ;)

Cheers!

**Comment by mbrevda** [comment]
Im sorry, I didn't realize you offered versioning. While I'm not sure I agree, I see why your doing it.

Thanks!

**Comment by keyvanakbary** [comment]
No prob! You're welcome :)

If you have any suggestions or issues with the code, you could open an issue. I promise I'll look into it :)

**Pull request merged**
