### PR TITLE
Turkish Update

### PR DESCRIPTION
**Pull request by TakaharaShujin**
2 Turkish letter big & small added : [ö,ö,Ü,ü]

### CODE REVIEW

**Comment by keyvanakbary** [comment]
Thanks for your commit!

It collides with the German characters, have you seen that?

**Comment by TakaharaShujin** [comment]
Yep i see, but Turkish "Ö" is not the same as the German "Ö".
For Example;
Title : "Bu bir örnektir"
Turkish sites should be used in the following way
TRSlug : "bu-bir-ornektir" [ö->o]
DESlug : "bu-bir-oernektir" [ö->oe]

**Comment by keyvanakbary** [comment]
I have an idea, as `ü` is also a common character for Spanish speakers that should be translated to `u`, why don't you add those characters in the Latin section and remove the German collisions?

**Comment by TakaharaShujin** [comment]
I think it makes more sense to add the language name parameter. Used as follows.
```php
\Slugifier::slugify("Sample sentence with ö and ü", "-","tr")
```

**Comment by keyvanakbary** [comment]
@TakaharaShujin I've been thinking about the best, reusable and simplest implementation for this and I came up with *modifiers* (PR #6).

Please, let me know what do you think :)

**Pull request closed without merging**
